_target_: pytorch_lightning.loggers.wandb.WandbLogger
entity: malteal
offline: True
id: null
log_model: False
project: pc-jet-diffusion
name: ${paths.name}
save_dir: ${paths.save_path}
tags:
  - ${data.name}
  - ${network_name}
  - VIPR
  - top_jet
  - RectifiedFlows 
