_target_: pytorch_lightning.Trainer

min_epochs: 1
max_epochs: 100
enable_progress_bar: True
accelerator: auto
devices: auto
gradient_clip_val: 5.0
precision: 32
check_val_every_n_epoch: 1

# Interpolated
default_root_dir: ${save_path}
