# Tag of Torch base image old 2.2.0-cuda11.7-cudnn8-runtime
# https://pypi.org/project/torch/
# https://hub.docker.com/r/pytorch/pytorch/tags
variables:
  TORCHTAG: 2.2.0-cuda12.1-cudnn8-runtime
  IMAGE_TYPE: otcalibbase:latest
  SLIM_IMAGE: python:3.10-slim

stages:
#  - linting
  - image_build_base
#  - unit_test
#  - coverage_test_stage
  - builds
  - image_build_otcalib
#  - publish
#  - pages


include:
#  - 'pipelines/.linting-gitlab-ci.yaml'
#  - 'pipelines/.unit_test-gitlab-ci.yaml'
  - 'pipelines/.docker-gitlab-ci.yaml'
#  - 'pipelines/.coverage-gitlab-ci.yaml'
