# Tag of TensorFlow base image
# https://pypi.org/project/tensorflow/#history
variables:
  TORCHTAG: 1.13.0-cuda11.6-cudnn8-runtime
  IMAGE_TYPE: otcalibbase:latest
  SLIM_IMAGE: python:3.8-slim

stages:
#  - linting
  - image_build_base
#  - unit_test
#  - coverage_test_stage
  - builds
  - image_build_otcalib
#  - publish
#  - pages


include:
#  - 'pipelines/.linting-gitlab-ci.yaml'
#  - 'pipelines/.unit_test-gitlab-ci.yaml'
  - 'pipelines/.docker-gitlab-ci.yaml'
#  - 'pipelines/.coverage-gitlab-ci.yaml'
