# decoder_cfg:
_target_: tools.transformers.transformer.Perceiver
_partial_: true
pcivr_cfg:
  latent_dim: 
    - 128 # n_cons
    - ${....upscale_dims} #features
  n_processes: 0
  dense_cfg: ${...dense_cfg}

  # encode to latent
  encode_cfg:
    model_dim: ${....upscale_dims}
    num_layers: 1
    mha_config: 
      attn_heads: ${model.attn_heads}
    init_self_attn: True
    dense_cfg: ${..dense_cfg}
    ctxt_dim: ${....upscale_dims}

  # latent back to start
  decode_cfg: ${.encode_cfg}

