_target_: tools.tools.transformers.transformer.TransformerDecoder
_partial_: true
model_dim: ${model.network.upscale_dims}
dense_cfg: ${model.network.dense_cfg}
num_layers: 1
mha_config: 
  attn_heads: 16
ctxt_dim: ${model.network.upscale_dims} 
init_self_attn: False
out_norm: False
