_target_: tools.tools.transformers.transformer.TransformerEncoder
_partial_: true
model_dim: ${model.network.upscale_dims}
dense_cfg: ${model.network.dense_cfg}
num_layers: 1
mha_config: 
  attn_heads: 8
ctxt_dim: ${model.network.upscale_dims}
out_norm: False
