_target_: tools.transformers.transformer.TransformerEncoder
_partial_: true
model_dim: ${..upscale_dims}
dense_cfg: ${..dense_cfg}
num_layers: 1
mha_config: 
  attn_heads: ${model.attn_heads}
ctxt_dim: ${..upscale_dims}
out_norm: False
