wandb_version: 1

_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=<class ''dict''>, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2023-05-25'', (''%H-%M-%S'',): ''08-59-43'',
    (''%Y_%m_%d'',): ''2023_05_25'', (''%H_%M_%S_%f'',): ''08_59_44_008102''}}), key_type=typing.Any,
    element_type=typing.Any)'
_parent:
  desc: null
  value: null
_flags_cache:
  desc: null
  value:
    struct: true
    convert: null
_content:
  desc: null
  value:
    save_path: ${path}/${now:%Y_%m_%d}_${now:%H_%M_%S_%f}
    path: /home/users/a/algren/scratch/trained_networks/diffusion/
    dataset_name: fashion
    dataset_repetitions: '5'
    num_epochs: '100'
    kid_image_size: '75'
    kid_diffusion_steps: '5'
    plot_diffusion_steps: '20'
    batch_size: '64'
    device: cuda
    unet_config: '{''embedding_dims'': 16, ''ctxt_dims'': 0, ''embedding_max_frequency'':
      1000.0, ''input_shape'': [1, 32, 32], ''channels'': [8, 16, 32, 64, 128], ''block_depth'':
      2, ''min_size'': 4, ''film_config'': {''N'': 64, ''n_layers'': 8, ''activation_str'':
      ''leaky_relu'', ''batchnorm'': True, ''device'': ''${device}''}, ''self_attention_cfg'':
      {''attn_below'': 8, ''device'': ''${device}'', ''attn_heads'': 16, ''pos_encode_kwargs'':
      {''embedding_max_frequency'': ''${unet_config.embedding_max_frequency}''}},
      ''cross_attention_cfg'': {''device'': ''${device}'', ''attn_heads'': 8, ''pos_encode_kwargs'':
      {''embedding_max_frequency'': ''${unet_config.embedding_max_frequency}''}}}'
    diffusion_config: '{''image_size'': 32, ''min_signal_rate'': 0.02, ''max_signal_rate'':
      0.95, ''batch_size'': ''${batch_size}'', ''ema'': 0.999, ''learning_rate'':
      0.001, ''weight_decay'': 0.0001}'
    wandb: '{''project'': ''unet-diffusion'', ''entity'': ''malteal''}'
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684997993.155054
    t:
      1:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.15.2
      8:
      - 5
