verbose: true
printshellcmds: true
jobs: 200 # Maximum number of jobs to run in parallel

executor: slurm
default-resources:
  slurm_account: golling
  slurm_partition: shared-cpu,private-dpnc-cpu,shared-bigmem,public-bigmem
  runtime: 600 # minutes
  mem_mb: 24000
  threads: 4
sdm: apptainer
apptainer-args: >- # multi-line string
  --nv
  --bind /srv,/home

# --env PYTHONPATH=.
# --cleanenv
# --env WANDB_API_KEY=$WANDB_API_KEY
