_target_: src.models.pc_model.PCDiffusion

device: ${device}

# input dims
vkq_dims: 3
embedding_cfg: ${trainer.embedding_cfg}
# ctxt_dims: null
upscale_dims: 256
num_layers: 14

dense_cfg:
  act_str: gelu
  n_layers: 2
  norm: layer

defaults:
  - _self_
  # - architectures@encoder_cfg: perceiver_cfg.yaml
  # - architectures@decoder_cfg: perceiver_cfg.yaml
  - architectures@encoder_cfg: trans_encoder.yaml
  - architectures@decoder_cfg: trans_decoder.yaml
