_target_: src.diffusion.TimeDependentAE
# _convert_: object

defaults:
  - _self_
  - architectures@network.encoder_cfg: trans_encoder.yaml
  - architectures@network.decoder_cfg: trans_decoder.yaml

train_config:
  opt_cfg:
    lr: 5e-4 # 0.0005
    weight_decay: 0.05

  lr_scheduler: 
    sch_type: "warmup_to_constant"
    attr:
      num_steps: 10_000
  
  loss_cfg:
    name: 'mse'
    args: {}

ema_sampler_val: 0.999

network: 
  _target_: src.models.pc_model.PCDiffusion

  device: ${device}
  
  # # evaluate
  eval_cfg:
    eval_iters: 10 # -1 is off
    n_diffusion_steps: 20
  
  # input dims
  vkq_dims: 3

  # embedding
  time_embedding: 
    _target_: tools.tools.positional_encoding.Sinusoidal
    embedding_dims: 64
    embedding_min_frequency: 0.0002
    embedding_max_frequency: 1

  ctxt_dims: 
    cnts: 3
    scalars: 6

  upscale_dims: 256
  num_layers: 2
  attn_heads: 16
  skip_cnt: True

  dense_cfg:
    act_str: gelu
    n_layers: 0
    norm: True
    nfactor: 2

