decoder_cfg:
  _target_: tools.transformers.transformer.Perceiver
  _partial_: true
  pcivr_cfg:
    latent_dim: 
      - 16 # n_cons
      - ${....upscale_dims} #features
    n_processes: 0
    dense_cfg: ${...dense_cfg}

    encode_cfg:
      model_dim: ${....upscale_dims}
      num_layers: 1
      mha_config: 
        attn_heads: 8
      init_self_attn: True
      dense_cfg: ${..dense_cfg}
      ctxt_dim: ${....upscale_dims}

    # process_cfg:       
    #   model_dim: ${....upscale_dims}
    #   num_layers: 1
    #   mha_config: 
    #     attn_heads: 8
    #   dense_cfg: ${....dense_cfg}
    #   ctxt_dim: ${....upscale_dims}

    decode_cfg: ${.encode_cfg}

encoder_cfg: ${.decoder_cfg}

  # film_cfg:
  #   ctxt_size: ${...embedding_cfg.embedding_dims}
  #   use_on_image: false
  #   dense_config:
  #     n_neurons: 512
  #     n_layers: 4
  #     activation_str: gelu
  #     batchnorm: true
  #     device: ${device}