decoder_cfg:
  _target_: tools.transformers.transformer.TransformerDecoder
  _partial_: true
  model_dim: ${..upscale_dims}
  dense_cfg: ${..dense_cfg}
  num_layers: 1
  mha_config: 
    attn_heads: 8
  ctxt_dim: ${..upscale_dims} 
  init_self_attn: True

encoder_cfg: 
  _target_: tools.transformers.transformer.TransformerEncoder
  _partial_: true
  model_dim: ${..upscale_dims}
  dense_cfg: ${..dense_cfg}
  num_layers: 1
  mha_config: 
    attn_heads: 8
  ctxt_dim: ${..upscale_dims}