_target_: src.models.pc_model.PileUpRemoval
_convert_: object

device: ${device}

# input dims
vkq_dims: 3
ctxt_dims: null
upscale_dims: 64
num_layers: 1

# denset network
dense_cfg:
  act_str: gelu
  n_layers: 2
  norm: layer

decoder_cfg:
  _target_: tools.transformers.transformer.UPerceiver
  _partial_: true
  cnts_sizes: [64,32,16]
  input_dim: 64
  model_dim: 128
  max_dims: 512
  device: cuda
  image_kwargs:
    unfold:
      kernel_size: 2
    fold: 
      output_size: [3, 64, 64]
      kernel_size: 2


  pcivr_cfg:
    device: ${...device} 
    n_processes: 0
    dense_cfg: ${...dense_cfg}

    encode_cfg:
      num_layers: 1
      mha_config: 
        attn_heads: 8
      init_self_attn: True
      dense_cfg: ${..dense_cfg}
      ctxt_dim: 0

    process_cfg:       
      num_layers: 1
      mha_config: 
        attn_heads: 8
      dense_cfg: ${..dense_cfg}
      ctxt_dim: 0

    decode_cfg: null
  