wandb_version: 1

_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=<class ''dict''>, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2023-05-27'', (''%H-%M-%S'',): ''14-07-18'',
    (''%Y_%m_%d'',): ''2023_05_27'', (''%H_%M_%S_%f'',): ''14_07_18_989905''}}), key_type=typing.Any,
    element_type=typing.Any)'
_parent:
  desc: null
  value: null
_flags_cache:
  desc: null
  value:
    struct: true
    convert: null
_content:
  desc: null
  value:
    path: /home/users/a/algren/scratch/trained_networks/diffusion/
    save_path: ${path}/${now:%Y_%m_%d}_${now:%H_%M_%S_%f}
    device: cuda
    wandb: '{''project'': ''unet-diffusion'', ''entity'': ''malteal'', ''mode'': ''online'',
      ''name'': ''afhq_v2_${now:%Y_%m_%d}_${now:%H_%M_%S_%f}''}'
    diffusion_config: '{''image_size'': 32, ''min_signal_rate'': 0.02, ''max_signal_rate'':
      0.95, ''ema'': 0.999, ''learning_rate'': 0.001, ''weight_decay'': 0.0001}'
    unet_config: '{''embedding_dims'': 32, ''ctxt_dims'': 0, ''embedding_max_frequency'':
      1000.0, ''input_shape'': [3, 64, 64], ''channels'': [8, 16, 32, 64, 128], ''block_depth'':
      2, ''min_size'': 4, ''dropout'': 0.1, ''use_gate'': True, ''film_config'': {''n_neurons'':
      64, ''n_layers'': 8, ''activation_str'': ''leaky_relu'', ''batchnorm'': True,
      ''device'': ''${device}''}, ''self_attention_cfg'': {''attn_below'': 8, ''device'':
      ''${device}'', ''attn_heads'': 16, ''pos_encode_kwargs'': {''embedding_max_frequency'':
      ''${unet_config.embedding_max_frequency}''}}, ''cross_attention_cfg'': {''attn_below'':
      16, ''device'': ''${device}'', ''attn_heads'': 16, ''pos_encode_kwargs'': {''embedding_max_frequency'':
      ''${unet_config.embedding_max_frequency}''}}}'
    _convert_: object
    train_set: '{''_target_'': ''torchvision.datasets.ImageFolder'', ''root'': ''/srv/beegfs/scratch/groups/rodem/datasets/afhq_v2/train/'',
      ''transform'': {''_target_'': ''torchvision.transforms.Compose'', ''transforms'':
      [{''_target_'': ''torchvision.transforms.Resize'', ''size'': 64}, {''_target_'':
      ''torchvision.transforms.RandomHorizontalFlip''}, {''_target_'': ''torchvision.transforms.ToTensor''}]}}'
    loader_cfg: '{''_target_'': ''torch.utils.data.DataLoader'', ''_partial_'': True,
      ''pin_memory'': True, ''batch_size'': 64, ''num_workers'': {''_target_'': ''torch.get_num_threads''},
      ''drop_last'': True, ''shuffle'': True}'
    num_epochs: '200'
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685189244.76593
    t:
      1:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.15.2
      8:
      - 5
