# @package _global_

defaults:
  - _self_

  - trainer: default.yaml
  - data: default.yaml
  - model: pc_diffusion.yaml
  # - model: image_diffusion.yaml
  # - eval: jet.yaml

  # - eval: mnist_pc.yaml

  - eval: default.yaml
  # # - model: unet_cfg.yaml
  # - model: u_perceiver_cfg.yaml

  - wandb: default.yaml
  - hydra: default.yaml
  - experiment: default.yaml

path: /home/users/a/algren/scratch/trained_networks/diffusion/${wandb.mode}/

save_path: ${path}/${wandb.name}

device: cuda