# @package _global_

hydra:
  run:
    dir: ${save_path}

defaults:
  - _self_
  - diffusion_cfg: default.yaml
  - model: pc_cfg.yaml
  
  - data_cfgs: pc_jet.yaml
  - eval: jet.yaml

  # - data_cfgs: pc_mnist.yaml
  # - eval: mnist_pc.yaml
  
  # - data_cfgs: pc_shapenet.yaml
  
  # - model: unet_cfg.yaml
  # - data_cfgs: animals.yaml

path: /home/users/a/algren/scratch/trained_networks/diffusion/
save_path: ${path}/${now:%Y_%m_%d}_${now:%H_%M_%S_%f}
device: cuda

wandb:
  project: pc-${..data_cfgs.data_name}-diffusion
  entity: malteal
  mode: offline # online offline
  name: ${..data_cfgs.data_name}_${now:%Y_%m_%d}_${now:%H_%M_%S_%f}

data_cfgs:
  standardize_bool: False
  loader_config:
    pin_memory: true
    batch_size: 128
    num_workers: 4
    drop_last: True
    shuffle: True
    # prefetch_factor: 8
    persistent_workers: True
    pin_memory_device: ${device}