# data
dataset_name : "oxford_flowers102"
dataset_repetitions : 5
num_epochs : 50  # train for at least 50 epochs for good results
# KID : Kernel Inception Distance, see related section
kid_image_size : 75
kid_diffusion_steps : 5
plot_diffusion_steps : 20
batch_size: 64
device: cuda

# architecture
unet_config:
  embedding_dims : 16
  embedding_max_frequency : 1000.0
  input_shape: [3, 32,32]
  channels : [3, 8, 16, 32]
  block_depth : 2

diffusion_config:
  # sampling
  image_size : 32
  min_signal_rate : 0.02
  max_signal_rate : 0.95

  # optimization
  batch_size : ${batch_size}
  ema : 0.999
  learning_rate : 1e-3
  weight_decay : 1e-4