# @package _global_
glob_path: /srv/beegfs/scratch/users/a/algren/trained_networks/diffusion/
obs_jets_path: /srv/beegfs/scratch/groups/rodem/pileup_diffusion/data/obs_jets/

jet_vars: ['eta', 'phi', 'pt', 'mass']
jet_sub_vars : ["tau_21", "tau_32", "d12", "d23", "d2", "mass", "pt"]


# glob settings
generate_substructure: True
n_post_to_gen: 1 # >1 generate posterior
combine_ctxt_size: 1
csv_sample_to_load: single #posterior_${eval.size} #single 
plot_images: True
save_figures: False
softdrop_path: /srv/beegfs/scratch/groups/rodem/pileup_diffusion/data/

# how to run eval fw
eval:
  _target_: run.plot_eval.EvaluatePhysics
  flow_path: jet_flow_2024_03_11_13_29_10_850955 # N(200, 10) correct normalization
  run_flow: True

  path_to_model: ${glob_path}/online/jet_2024_02_12_15_29_33_272016 # N(200, 10) correct normalization
  # path_to_model: ${glob_path}/online/jet_2024_02_17_14_17_07_224394 # N(60, 10) correct normalization

  path_lst:
    N(200, 50): ${glob_path}/online/jet_2024_02_12_15_29_33_272016 # N(200, 10) correct normalization
    N(60, 10):  ${glob_path}/online/jet_2024_02_17_14_17_07_224394 # N(60, 10) correct normalization

  size: 10_000 # 100_000 / 2000
  device: cpu
  format: ".pdf"

  data_cfg: 
    pileup_dist_args:
      mu: 300 # 50, 60, 70, 80, 90, 100, 150, 200, 250, 300
      std: 0 # 50 or 0 


  loader_config:
    batch_size: 512
    num_workers: 4
  
  eval_cfg:
    n_diffusion_steps: 100


# plot settings
hist_kwargs:
  style:
    bins: 35
  percentile_lst: [0.1, 99]
  dist_styles:
    - label: Top
      color: black

    - label: SoftDrop
      color: green

    - label: Obs.
      color: red

    # - label: Vipr
    #   color: blue

    - label: 'VIPR'
      color: blue
      # ls: dashed

ratio_kwargs:
  styles: 
    - color: black
    - color: green
    - color: red
    # - color: blue
    - color: blue
