train:
  _target_: src.physics.JetPhysics
  _convert_: object
  jet_path: [/home/users/a/algren/scratch/diffusion/pileup/ttbar.csv, ]
  pileup_path: ["/home/users/a/algren/scratch/diffusion/pileup/pileup.csv", ]

  target_names: ['eta', 'phi', 'pt']
  jet_scalars_cols: ["eta", "phi", "pt", "mass"]

  data_name: jet

  noise_to_pileup: 0.0