# _target_: src.pipeline.PointCloudModule
# _convert_: object

# train_path: [/home/users/a/algren/scratch/diffusion/pileup/ttbar_processed.csv, ]
# test_path: [/home/users/a/algren/scratch/diffusion/pileup/ttbar_processed.csv, ]

# data_name: jet
_target_: src.physics.JetPhysics
_convert_: object

jet_path: [/home/users/a/algren/scratch/diffusion/pileup/ttbar.csv, ]
pileup_path: ["/home/users/a/algren/scratch/diffusion/pileup/pileup.csv", ]

data_name: jet
