
data_name: jet

train:
  _target_: src.physics.MultiJetFiles
  _convert_: object

  jet_path: /srv/beegfs/scratch/groups/rodem/datasets/pileup_jets/top/path_lists.yaml

  sub_col: train
  n_files: null
  n_pileup_to_select: 100

  # variables used
  target_names: ['eta', 'phi', 'pt']
  
  # ctxt variables
  jet_scalars_cols: ["eta", "phi", "pt", "mass"]

  # if the pileup path in defined - it will use pileup path
  pileup_path: ["/home/users/a/algren/scratch/diffusion/pileup/pileup.csv", ]

  max_cnstits: 400

valid:
  _target_: src.physics.JetPhysics
  _convert_: object

  jet_path: ${..train.jet_path}
  sub_col: train
  n_files: 1
  n_pileup_to_select: ${..train.n_pileup_to_select}

  pileup_path: ${..train.pileup_path}

  target_names: ${..train.target_names}
  jet_scalars_cols: ${..train.jet_scalars_cols}

  # max_cnstits: 271
